# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.api.admin_search_api import AdminSearchApi


class TestAdminSearchApi(unittest.TestCase):
    """AdminSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminSearchApi()

    def tearDown(self) -> None:
        pass

    def test_admin_search_queries_country_id_get(self) -> None:
        """Test case for admin_search_queries_country_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
