# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_search_get_search_queries_response200_data import AdminSearchGetSearchQueriesResponse200Data

class TestAdminSearchGetSearchQueriesResponse200Data(unittest.TestCase):
    """AdminSearchGetSearchQueriesResponse200Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSearchGetSearchQueriesResponse200Data:
        """Test AdminSearchGetSearchQueriesResponse200Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSearchGetSearchQueriesResponse200Data`
        """
        model = AdminSearchGetSearchQueriesResponse200Data()
        if include_optional:
            return AdminSearchGetSearchQueriesResponse200Data(
                queries = [
                    realzilla.client.models.external_search_query.ExternalSearchQuery(
                        id = '', 
                        text = '', 
                        status = 'NEW', )
                    ]
            )
        else:
            return AdminSearchGetSearchQueriesResponse200Data(
                queries = [
                    realzilla.client.models.external_search_query.ExternalSearchQuery(
                        id = '', 
                        text = '', 
                        status = 'NEW', )
                    ],
        )
        """

    def testAdminSearchGetSearchQueriesResponse200Data(self):
        """Test AdminSearchGetSearchQueriesResponse200Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
