# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_web_webpages_post4_xx_response import AdminWebWebpagesPost4XXResponse

class TestAdminWebWebpagesPost4XXResponse(unittest.TestCase):
    """AdminWebWebpagesPost4XXResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminWebWebpagesPost4XXResponse:
        """Test AdminWebWebpagesPost4XXResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminWebWebpagesPost4XXResponse`
        """
        model = AdminWebWebpagesPost4XXResponse()
        if include_optional:
            return AdminWebWebpagesPost4XXResponse(
                success = True,
                error = '',
                error_code = ''
            )
        else:
            return AdminWebWebpagesPost4XXResponse(
                success = True,
                error = '',
                error_code = '',
        )
        """

    def testAdminWebWebpagesPost4XXResponse(self):
        """Test AdminWebWebpagesPost4XXResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
