# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.geo_get_country_by_code_response import GeoGetCountryByCodeResponse

class TestGeoGetCountryByCodeResponse(unittest.TestCase):
    """GeoGetCountryByCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoGetCountryByCodeResponse:
        """Test GeoGetCountryByCodeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoGetCountryByCodeResponse`
        """
        model = GeoGetCountryByCodeResponse()
        if include_optional:
            return GeoGetCountryByCodeResponse(
                var_200 = realzilla.client.models._geo_countries__country_code__get_200_response._geo_countries__countryCode__get_200_response(
                    success = True, 
                    data = realzilla.client.models._geo_countries__country_code__get_200_response_data._geo_countries__countryCode__get_200_response_data(
                        country = realzilla.client.models.external_country.ExternalCountry(
                            id = '', 
                            code = 'AD', 
                            name = '', 
                            name_normalized = '', 
                            population = 1.337, 
                            surface = 1.337, 
                            administrative_level1_type = null, 
                            administrative_level1_name = '', 
                            administrative_level2_type = null, 
                            administrative_level2_name = '', 
                            administrative_level3_type = null, 
                            administrative_level3_name = '', 
                            administrative_level4_type = null, 
                            administrative_level4_name = '', ), ), ),
                var_4xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
                var_5xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', )
            )
        else:
            return GeoGetCountryByCodeResponse(
                var_200 = realzilla.client.models._geo_countries__country_code__get_200_response._geo_countries__countryCode__get_200_response(
                    success = True, 
                    data = realzilla.client.models._geo_countries__country_code__get_200_response_data._geo_countries__countryCode__get_200_response_data(
                        country = realzilla.client.models.external_country.ExternalCountry(
                            id = '', 
                            code = 'AD', 
                            name = '', 
                            name_normalized = '', 
                            population = 1.337, 
                            surface = 1.337, 
                            administrative_level1_type = null, 
                            administrative_level1_name = '', 
                            administrative_level2_type = null, 
                            administrative_level2_name = '', 
                            administrative_level3_type = null, 
                            administrative_level3_name = '', 
                            administrative_level4_type = null, 
                            administrative_level4_name = '', ), ), ),
                var_4xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
                var_5xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
        )
        """

    def testGeoGetCountryByCodeResponse(self):
        """Test GeoGetCountryByCodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
