# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_area import ExternalArea

class TestExternalArea(unittest.TestCase):
    """ExternalArea unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalArea:
        """Test ExternalArea
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalArea`
        """
        model = ExternalArea()
        if include_optional:
            return ExternalArea(
                id = '',
                name = '',
                type = 'QUARTER'
            )
        else:
            return ExternalArea(
                id = '',
                name = '',
                type = 'QUARTER',
        )
        """

    def testExternalArea(self):
        """Test ExternalArea"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
