# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_search_queries_country_id_get200_response_data import AdminSearchQueriesCountryIdGet200ResponseData

class TestAdminSearchQueriesCountryIdGet200ResponseData(unittest.TestCase):
    """AdminSearchQueriesCountryIdGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSearchQueriesCountryIdGet200ResponseData:
        """Test AdminSearchQueriesCountryIdGet200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSearchQueriesCountryIdGet200ResponseData`
        """
        model = AdminSearchQueriesCountryIdGet200ResponseData()
        if include_optional:
            return AdminSearchQueriesCountryIdGet200ResponseData(
                queries = [
                    realzilla.client.models.external_search_query.ExternalSearchQuery(
                        id = '', 
                        text = '', 
                        status = 'NEW', 
                        population = 1.337, 
                        search_entry = realzilla.client.models.external_search_entry.ExternalSearchEntry(
                            id = '', 
                            type = 'WEBSITE', 
                            text = '', 
                            level = 'COUNTRY', ), 
                        city = null, 
                        country = realzilla.client.models.external_country.ExternalCountry(
                            id = '', 
                            code = 'AD', 
                            name = '', 
                            name_normalized = '', 
                            population = 1.337, 
                            surface = 1.337, 
                            administrative_level1_type = null, 
                            administrative_level1_name = '', 
                            administrative_level2_type = null, 
                            administrative_level2_name = '', 
                            administrative_level3_type = null, 
                            administrative_level3_name = '', 
                            administrative_level4_type = null, 
                            administrative_level4_name = '', ), )
                    ]
            )
        else:
            return AdminSearchQueriesCountryIdGet200ResponseData(
                queries = [
                    realzilla.client.models.external_search_query.ExternalSearchQuery(
                        id = '', 
                        text = '', 
                        status = 'NEW', 
                        population = 1.337, 
                        search_entry = realzilla.client.models.external_search_entry.ExternalSearchEntry(
                            id = '', 
                            type = 'WEBSITE', 
                            text = '', 
                            level = 'COUNTRY', ), 
                        city = null, 
                        country = realzilla.client.models.external_country.ExternalCountry(
                            id = '', 
                            code = 'AD', 
                            name = '', 
                            name_normalized = '', 
                            population = 1.337, 
                            surface = 1.337, 
                            administrative_level1_type = null, 
                            administrative_level1_name = '', 
                            administrative_level2_type = null, 
                            administrative_level2_name = '', 
                            administrative_level3_type = null, 
                            administrative_level3_name = '', 
                            administrative_level4_type = null, 
                            administrative_level4_name = '', ), )
                    ],
        )
        """

    def testAdminSearchQueriesCountryIdGet200ResponseData(self):
        """Test AdminSearchQueriesCountryIdGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
