# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_administrative_level_shallow import ExternalAdministrativeLevelShallow

class TestExternalAdministrativeLevelShallow(unittest.TestCase):
    """ExternalAdministrativeLevelShallow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalAdministrativeLevelShallow:
        """Test ExternalAdministrativeLevelShallow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalAdministrativeLevelShallow`
        """
        model = ExternalAdministrativeLevelShallow()
        if include_optional:
            return ExternalAdministrativeLevelShallow(
                id = '',
                name = '',
                name_normalized = '',
                level = 1.337,
                code = ''
            )
        else:
            return ExternalAdministrativeLevelShallow(
                id = '',
                name = '',
                name_normalized = '',
                level = 1.337,
                code = '',
        )
        """

    def testExternalAdministrativeLevelShallow(self):
        """Test ExternalAdministrativeLevelShallow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
