# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.api.geo_api import GeoApi


class TestGeoApi(unittest.TestCase):
    """GeoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GeoApi()

    def tearDown(self) -> None:
        pass

    def test_geo_countries_country_code_get(self) -> None:
        """Test case for geo_countries_country_code_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
