# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_agent import ExternalAgent

class TestExternalAgent(unittest.TestCase):
    """ExternalAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalAgent:
        """Test ExternalAgent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalAgent`
        """
        model = ExternalAgent()
        if include_optional:
            return ExternalAgent(
                id = '',
                first_name = '',
                last_name = '',
                is_active = True
            )
        else:
            return ExternalAgent(
                id = '',
                first_name = '',
                last_name = '',
                is_active = True,
        )
        """

    def testExternalAgent(self):
        """Test ExternalAgent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
