# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_web_webpages_post2_xx_response import AdminWebWebpagesPost2XXResponse

class TestAdminWebWebpagesPost2XXResponse(unittest.TestCase):
    """AdminWebWebpagesPost2XXResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminWebWebpagesPost2XXResponse:
        """Test AdminWebWebpagesPost2XXResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminWebWebpagesPost2XXResponse`
        """
        model = AdminWebWebpagesPost2XXResponse()
        if include_optional:
            return AdminWebWebpagesPost2XXResponse(
                success = True,
                message = ''
            )
        else:
            return AdminWebWebpagesPost2XXResponse(
                success = True,
        )
        """

    def testAdminWebWebpagesPost2XXResponse(self):
        """Test AdminWebWebpagesPost2XXResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
