# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_administrative_level import ExternalAdministrativeLevel

class TestExternalAdministrativeLevel(unittest.TestCase):
    """ExternalAdministrativeLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalAdministrativeLevel:
        """Test ExternalAdministrativeLevel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalAdministrativeLevel`
        """
        model = ExternalAdministrativeLevel()
        if include_optional:
            return ExternalAdministrativeLevel(
                id = '',
                name = '',
                name_normalized = '',
                level = 1.337,
                code = '',
                parent = realzilla.client.models.external_administrative_level.ExternalAdministrativeLevel(
                    id = '', 
                    name = '', 
                    name_normalized = '', 
                    level = 1.337, 
                    code = '', 
                    parent = null, )
            )
        else:
            return ExternalAdministrativeLevel(
                id = '',
                name = '',
                name_normalized = '',
                level = 1.337,
                code = '',
        )
        """

    def testExternalAdministrativeLevel(self):
        """Test ExternalAdministrativeLevel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
