# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.search_query_status import SearchQueryStatus

class TestSearchQueryStatus(unittest.TestCase):
    """SearchQueryStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchQueryStatus(self):
        """Test SearchQueryStatus"""
        # inst = SearchQueryStatus()

if __name__ == '__main__':
    unittest.main()
