# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.search_entry_type import SearchEntryType

class TestSearchEntryType(unittest.TestCase):
    """SearchEntryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchEntryType(self):
        """Test SearchEntryType"""
        # inst = SearchEntryType()

if __name__ == '__main__':
    unittest.main()
