# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.geo_get_country_by_code_response200_data import GeoGetCountryByCodeResponse200Data

class TestGeoGetCountryByCodeResponse200Data(unittest.TestCase):
    """GeoGetCountryByCodeResponse200Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoGetCountryByCodeResponse200Data:
        """Test GeoGetCountryByCodeResponse200Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoGetCountryByCodeResponse200Data`
        """
        model = GeoGetCountryByCodeResponse200Data()
        if include_optional:
            return GeoGetCountryByCodeResponse200Data(
                country = realzilla.client.models.external_country.ExternalCountry(
                    id = '', 
                    code = 'AD', 
                    name = '', 
                    name_normalized = '', 
                    population = 1.337, 
                    surface = 1.337, 
                    administrative_level1_type = null, 
                    administrative_level1_name = '', 
                    administrative_level2_type = null, 
                    administrative_level2_name = '', 
                    administrative_level3_type = null, 
                    administrative_level3_name = '', 
                    administrative_level4_type = null, 
                    administrative_level4_name = '', )
            )
        else:
            return GeoGetCountryByCodeResponse200Data(
                country = realzilla.client.models.external_country.ExternalCountry(
                    id = '', 
                    code = 'AD', 
                    name = '', 
                    name_normalized = '', 
                    population = 1.337, 
                    surface = 1.337, 
                    administrative_level1_type = null, 
                    administrative_level1_name = '', 
                    administrative_level2_type = null, 
                    administrative_level2_name = '', 
                    administrative_level3_type = null, 
                    administrative_level3_name = '', 
                    administrative_level4_type = null, 
                    administrative_level4_name = '', ),
        )
        """

    def testGeoGetCountryByCodeResponse200Data(self):
        """Test GeoGetCountryByCodeResponse200Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
