# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_agency import ExternalAgency

class TestExternalAgency(unittest.TestCase):
    """ExternalAgency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalAgency:
        """Test ExternalAgency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalAgency`
        """
        model = ExternalAgency()
        if include_optional:
            return ExternalAgency(
                id = '',
                name = '',
                type = 'FRANCHISE'
            )
        else:
            return ExternalAgency(
                id = '',
                name = '',
                type = 'FRANCHISE',
        )
        """

    def testExternalAgency(self):
        """Test ExternalAgency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
