# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.default_simple_response import DefaultSimpleResponse

class TestDefaultSimpleResponse(unittest.TestCase):
    """DefaultSimpleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultSimpleResponse:
        """Test DefaultSimpleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultSimpleResponse`
        """
        model = DefaultSimpleResponse()
        if include_optional:
            return DefaultSimpleResponse(
                var_2xx = realzilla.client.models.simple_response.SimpleResponse(
                    success = True, 
                    message = '', ),
                var_4xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
                var_5xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', )
            )
        else:
            return DefaultSimpleResponse(
                var_2xx = realzilla.client.models.simple_response.SimpleResponse(
                    success = True, 
                    message = '', ),
                var_4xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
                var_5xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
        )
        """

    def testDefaultSimpleResponse(self):
        """Test DefaultSimpleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
