# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_search_queries_country_id_get200_response_data_queries_inner import AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner

class TestAdminSearchQueriesCountryIdGet200ResponseDataQueriesInner(unittest.TestCase):
    """AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner:
        """Test AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner`
        """
        model = AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner()
        if include_optional:
            return AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner(
                id = '',
                text = '',
                status = 'NEW'
            )
        else:
            return AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner(
                id = '',
                text = '',
                status = 'NEW',
        )
        """

    def testAdminSearchQueriesCountryIdGet200ResponseDataQueriesInner(self):
        """Test AdminSearchQueriesCountryIdGet200ResponseDataQueriesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
