# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_search_get_search_queries_response import AdminSearchGetSearchQueriesResponse

class TestAdminSearchGetSearchQueriesResponse(unittest.TestCase):
    """AdminSearchGetSearchQueriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSearchGetSearchQueriesResponse:
        """Test AdminSearchGetSearchQueriesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSearchGetSearchQueriesResponse`
        """
        model = AdminSearchGetSearchQueriesResponse()
        if include_optional:
            return AdminSearchGetSearchQueriesResponse(
                var_200 = realzilla.client.models._admin_search_queries__country_id__get_200_response._admin_search_queries__countryId__get_200_response(
                    success = True, 
                    data = realzilla.client.models._admin_search_queries__country_id__get_200_response_data._admin_search_queries__countryId__get_200_response_data(
                        queries = [
                            realzilla.client.models.external_search_query.ExternalSearchQuery(
                                id = '', 
                                text = '', 
                                status = 'NEW', 
                                population = 1.337, 
                                search_entry = realzilla.client.models.external_search_entry.ExternalSearchEntry(
                                    id = '', 
                                    type = 'WEBSITE', 
                                    text = '', 
                                    level = 'COUNTRY', ), 
                                city = null, 
                                country = realzilla.client.models.external_country.ExternalCountry(
                                    id = '', 
                                    code = 'AD', 
                                    name = '', 
                                    name_normalized = '', 
                                    population = 1.337, 
                                    surface = 1.337, 
                                    administrative_level1_type = null, 
                                    administrative_level1_name = '', 
                                    administrative_level2_type = null, 
                                    administrative_level2_name = '', 
                                    administrative_level3_type = null, 
                                    administrative_level3_name = '', 
                                    administrative_level4_type = null, 
                                    administrative_level4_name = '', ), )
                            ], ), ),
                var_4xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
                var_5xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', )
            )
        else:
            return AdminSearchGetSearchQueriesResponse(
                var_200 = realzilla.client.models._admin_search_queries__country_id__get_200_response._admin_search_queries__countryId__get_200_response(
                    success = True, 
                    data = realzilla.client.models._admin_search_queries__country_id__get_200_response_data._admin_search_queries__countryId__get_200_response_data(
                        queries = [
                            realzilla.client.models.external_search_query.ExternalSearchQuery(
                                id = '', 
                                text = '', 
                                status = 'NEW', 
                                population = 1.337, 
                                search_entry = realzilla.client.models.external_search_entry.ExternalSearchEntry(
                                    id = '', 
                                    type = 'WEBSITE', 
                                    text = '', 
                                    level = 'COUNTRY', ), 
                                city = null, 
                                country = realzilla.client.models.external_country.ExternalCountry(
                                    id = '', 
                                    code = 'AD', 
                                    name = '', 
                                    name_normalized = '', 
                                    population = 1.337, 
                                    surface = 1.337, 
                                    administrative_level1_type = null, 
                                    administrative_level1_name = '', 
                                    administrative_level2_type = null, 
                                    administrative_level2_name = '', 
                                    administrative_level3_type = null, 
                                    administrative_level3_name = '', 
                                    administrative_level4_type = null, 
                                    administrative_level4_name = '', ), )
                            ], ), ),
                var_4xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
                var_5xx = realzilla.client.models.error_response.ErrorResponse(
                    success = True, 
                    error = '', 
                    error_code = '', ),
        )
        """

    def testAdminSearchGetSearchQueriesResponse(self):
        """Test AdminSearchGetSearchQueriesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
