# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_search_get_search_queries_request import AdminSearchGetSearchQueriesRequest

class TestAdminSearchGetSearchQueriesRequest(unittest.TestCase):
    """AdminSearchGetSearchQueriesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSearchGetSearchQueriesRequest:
        """Test AdminSearchGetSearchQueriesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSearchGetSearchQueriesRequest`
        """
        model = AdminSearchGetSearchQueriesRequest()
        if include_optional:
            return AdminSearchGetSearchQueriesRequest(
                start = 0,
                limit = 1,
                country_id = ''
            )
        else:
            return AdminSearchGetSearchQueriesRequest(
                country_id = '',
        )
        """

    def testAdminSearchGetSearchQueriesRequest(self):
        """Test AdminSearchGetSearchQueriesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
