# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_web_webpages_post_request import AdminWebWebpagesPostRequest

class TestAdminWebWebpagesPostRequest(unittest.TestCase):
    """AdminWebWebpagesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminWebWebpagesPostRequest:
        """Test AdminWebWebpagesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminWebWebpagesPostRequest`
        """
        model = AdminWebWebpagesPostRequest()
        if include_optional:
            return AdminWebWebpagesPostRequest(
                country_id = '',
                webpages = [
                    realzilla.client.models.valid_url_with_title.ValidURLWithTitle(
                        url = '', 
                        title = '', )
                    ]
            )
        else:
            return AdminWebWebpagesPostRequest(
                country_id = '',
                webpages = [
                    realzilla.client.models.valid_url_with_title.ValidURLWithTitle(
                        url = '', 
                        title = '', )
                    ],
        )
        """

    def testAdminWebWebpagesPostRequest(self):
        """Test AdminWebWebpagesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
