# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_address import ExternalAddress

class TestExternalAddress(unittest.TestCase):
    """ExternalAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalAddress:
        """Test ExternalAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalAddress`
        """
        model = ExternalAddress()
        if include_optional:
            return ExternalAddress(
                id = '',
                street_address = '',
                city = realzilla.client.models.external_city.ExternalCity(
                    id = '', 
                    code = '', 
                    name = '', 
                    name_normalized = '', 
                    status = 'ACTIVE', 
                    population = 1.337, 
                    surface = 1.337, 
                    density = 1.337, 
                    administrative_level1 = null, 
                    administrative_level2 = null, 
                    administrative_level3 = null, 
                    administrative_level4 = null, )
            )
        else:
            return ExternalAddress(
                id = '',
                street_address = '',
        )
        """

    def testExternalAddress(self):
        """Test ExternalAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
