# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.admin_search_queries_get200_response_data import AdminSearchQueriesGet200ResponseData

class TestAdminSearchQueriesGet200ResponseData(unittest.TestCase):
    """AdminSearchQueriesGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminSearchQueriesGet200ResponseData:
        """Test AdminSearchQueriesGet200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminSearchQueriesGet200ResponseData`
        """
        model = AdminSearchQueriesGet200ResponseData()
        if include_optional:
            return AdminSearchQueriesGet200ResponseData(
                queries = [
                    realzilla.client.models._admin_search_queries_get_200_response_data_queries_inner._admin_search_queries_get_200_response_data_queries_inner(
                        id = '', 
                        text = '', 
                        status = 'NEW', )
                    ]
            )
        else:
            return AdminSearchQueriesGet200ResponseData(
                queries = [
                    realzilla.client.models._admin_search_queries_get_200_response_data_queries_inner._admin_search_queries_get_200_response_data_queries_inner(
                        id = '', 
                        text = '', 
                        status = 'NEW', )
                    ],
        )
        """

    def testAdminSearchQueriesGet200ResponseData(self):
        """Test AdminSearchQueriesGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
