# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.property_status import PropertyStatus

class TestPropertyStatus(unittest.TestCase):
    """PropertyStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropertyStatus(self):
        """Test PropertyStatus"""
        # inst = PropertyStatus()

if __name__ == '__main__':
    unittest.main()
