# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_search_query import ExternalSearchQuery

class TestExternalSearchQuery(unittest.TestCase):
    """ExternalSearchQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalSearchQuery:
        """Test ExternalSearchQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalSearchQuery`
        """
        model = ExternalSearchQuery()
        if include_optional:
            return ExternalSearchQuery(
                id = '',
                text = '',
                status = 'NEW',
                population = 1.337,
                search_entry = realzilla.client.models.external_search_entry.ExternalSearchEntry(
                    id = '', 
                    type = 'WEBSITE', 
                    text = '', 
                    level = 'COUNTRY', ),
                city = realzilla.client.models.external_city.ExternalCity(
                    id = '', 
                    code = '', 
                    name = '', 
                    name_normalized = '', 
                    status = 'ACTIVE', 
                    population = 1.337, 
                    surface = 1.337, 
                    density = 1.337, 
                    administrative_level1 = null, 
                    administrative_level2 = null, 
                    administrative_level3 = null, 
                    administrative_level4 = null, ),
                country = realzilla.client.models.external_country.ExternalCountry(
                    id = '', 
                    code = 'AD', 
                    name = '', 
                    name_normalized = '', 
                    population = 1.337, 
                    surface = 1.337, 
                    administrative_level1_type = null, 
                    administrative_level1_name = '', 
                    administrative_level2_type = null, 
                    administrative_level2_name = '', 
                    administrative_level3_type = null, 
                    administrative_level3_name = '', 
                    administrative_level4_type = null, 
                    administrative_level4_name = '', )
            )
        else:
            return ExternalSearchQuery(
                id = '',
                text = '',
                status = 'NEW',
                population = 1.337,
        )
        """

    def testExternalSearchQuery(self):
        """Test ExternalSearchQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
