# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.heating_type import HeatingType

class TestHeatingType(unittest.TestCase):
    """HeatingType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeatingType(self):
        """Test HeatingType"""
        # inst = HeatingType()

if __name__ == '__main__':
    unittest.main()
