# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_listing import ExternalListing

class TestExternalListing(unittest.TestCase):
    """ExternalListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalListing:
        """Test ExternalListing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalListing`
        """
        model = ExternalListing()
        if include_optional:
            return ExternalListing(
                id = '',
                status = 'NEW',
                url = '',
                title = '',
                description = '',
                price_listed = '',
                agency_fee = '',
                agency_commission = '',
                info_year = 1.337,
                info_pool = True,
                info_elevator = True,
                info_floor = 1.337,
                info_num_floors = 1.337,
                info_heating = 'NONE',
                info_terrace = True,
                file_path = '',
                var_property = realzilla.client.models.external_property.ExternalProperty(
                    id = '', 
                    type = 'RESIDENTIAL', 
                    status = 'NEW', 
                    name = '', ),
                agent1 = realzilla.client.models.external_agent.ExternalAgent(
                    id = '', 
                    first_name = '', 
                    last_name = '', 
                    is_active = True, ),
                agent2 = realzilla.client.models.external_agent.ExternalAgent(
                    id = '', 
                    first_name = '', 
                    last_name = '', 
                    is_active = True, ),
                agency = realzilla.client.models.external_agency.ExternalAgency(
                    id = '', 
                    name = '', 
                    type = 'FRANCHISE', ),
                agency_parent = realzilla.client.models.external_agency.ExternalAgency(
                    id = '', 
                    name = '', 
                    type = 'FRANCHISE', )
            )
        else:
            return ExternalListing(
                id = '',
                status = 'NEW',
                url = '',
                title = '',
                description = '',
                price_listed = '',
                agency_fee = '',
                agency_commission = '',
                info_year = 1.337,
                info_pool = True,
                info_elevator = True,
                info_floor = 1.337,
                info_num_floors = 1.337,
                info_heating = 'NONE',
                info_terrace = True,
                file_path = '',
        )
        """

    def testExternalListing(self):
        """Test ExternalListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
