# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_search_query import ExternalSearchQuery

class TestExternalSearchQuery(unittest.TestCase):
    """ExternalSearchQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalSearchQuery:
        """Test ExternalSearchQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalSearchQuery`
        """
        model = ExternalSearchQuery()
        if include_optional:
            return ExternalSearchQuery(
                id = '',
                text = '',
                status = 'NEW'
            )
        else:
            return ExternalSearchQuery(
                id = '',
                text = '',
                status = 'NEW',
        )
        """

    def testExternalSearchQuery(self):
        """Test ExternalSearchQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
