# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.geo_countries_country_code_get200_response_data_country import GeoCountriesCountryCodeGet200ResponseDataCountry

class TestGeoCountriesCountryCodeGet200ResponseDataCountry(unittest.TestCase):
    """GeoCountriesCountryCodeGet200ResponseDataCountry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoCountriesCountryCodeGet200ResponseDataCountry:
        """Test GeoCountriesCountryCodeGet200ResponseDataCountry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoCountriesCountryCodeGet200ResponseDataCountry`
        """
        model = GeoCountriesCountryCodeGet200ResponseDataCountry()
        if include_optional:
            return GeoCountriesCountryCodeGet200ResponseDataCountry(
                id = '',
                code = 'AD',
                name = '',
                name_normalized = '',
                population = 1.337,
                surface = 1.337,
                administrative_level1_type = 'STATE',
                administrative_level1_name = '',
                administrative_level2_type = 'STATE',
                administrative_level2_name = '',
                administrative_level3_type = 'STATE',
                administrative_level3_name = '',
                administrative_level4_type = 'STATE',
                administrative_level4_name = ''
            )
        else:
            return GeoCountriesCountryCodeGet200ResponseDataCountry(
                id = '',
                code = 'AD',
                name = '',
                name_normalized = '',
                population = 1.337,
                surface = 1.337,
                administrative_level1_type = 'STATE',
                administrative_level1_name = '',
                administrative_level2_type = 'STATE',
                administrative_level2_name = '',
                administrative_level3_type = 'STATE',
                administrative_level3_name = '',
                administrative_level4_type = 'STATE',
                administrative_level4_name = '',
        )
        """

    def testGeoCountriesCountryCodeGet200ResponseDataCountry(self):
        """Test GeoCountriesCountryCodeGet200ResponseDataCountry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
