# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_search_entry import ExternalSearchEntry

class TestExternalSearchEntry(unittest.TestCase):
    """ExternalSearchEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalSearchEntry:
        """Test ExternalSearchEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalSearchEntry`
        """
        model = ExternalSearchEntry()
        if include_optional:
            return ExternalSearchEntry(
                id = '',
                type = 'WEBSITE',
                text = '',
                level = 'COUNTRY'
            )
        else:
            return ExternalSearchEntry(
                id = '',
                type = 'WEBSITE',
                text = '',
                level = 'COUNTRY',
        )
        """

    def testExternalSearchEntry(self):
        """Test ExternalSearchEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
