# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.listing_status import ListingStatus

class TestListingStatus(unittest.TestCase):
    """ListingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListingStatus(self):
        """Test ListingStatus"""
        # inst = ListingStatus()

if __name__ == '__main__':
    unittest.main()
