# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_country import ExternalCountry

class TestExternalCountry(unittest.TestCase):
    """ExternalCountry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalCountry:
        """Test ExternalCountry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalCountry`
        """
        model = ExternalCountry()
        if include_optional:
            return ExternalCountry(
                id = '',
                code = 'AD',
                name = '',
                name_normalized = '',
                population = 1.337,
                surface = 1.337,
                administrative_level1_type = 'STATE',
                administrative_level1_name = '',
                administrative_level2_type = 'STATE',
                administrative_level2_name = '',
                administrative_level3_type = 'STATE',
                administrative_level3_name = '',
                administrative_level4_type = 'STATE',
                administrative_level4_name = ''
            )
        else:
            return ExternalCountry(
                id = '',
                code = 'AD',
                name = '',
                name_normalized = '',
                population = 1.337,
                surface = 1.337,
                administrative_level1_type = 'STATE',
                administrative_level1_name = '',
                administrative_level2_type = 'STATE',
                administrative_level2_name = '',
                administrative_level3_type = 'STATE',
                administrative_level3_name = '',
                administrative_level4_type = 'STATE',
                administrative_level4_name = '',
        )
        """

    def testExternalCountry(self):
        """Test ExternalCountry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
