# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.geo_get_country_by_code_params import GeoGetCountryByCodeParams

class TestGeoGetCountryByCodeParams(unittest.TestCase):
    """GeoGetCountryByCodeParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoGetCountryByCodeParams:
        """Test GeoGetCountryByCodeParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoGetCountryByCodeParams`
        """
        model = GeoGetCountryByCodeParams()
        if include_optional:
            return GeoGetCountryByCodeParams(
                country_code = 'AD'
            )
        else:
            return GeoGetCountryByCodeParams(
                country_code = 'AD',
        )
        """

    def testGeoGetCountryByCodeParams(self):
        """Test GeoGetCountryByCodeParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
