# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.external_city import ExternalCity

class TestExternalCity(unittest.TestCase):
    """ExternalCity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalCity:
        """Test ExternalCity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalCity`
        """
        model = ExternalCity()
        if include_optional:
            return ExternalCity(
                id = '',
                code = '',
                name = '',
                name_normalized = '',
                status = 'ACTIVE',
                population = 1.337,
                surface = 1.337,
                density = 1.337,
                administrative_level1 = realzilla.client.models.external_administrative_level_shallow.ExternalAdministrativeLevelShallow(
                    id = '', 
                    name = '', 
                    name_normalized = '', 
                    level = 1.337, 
                    code = '', ),
                administrative_level2 = realzilla.client.models.external_administrative_level_shallow.ExternalAdministrativeLevelShallow(
                    id = '', 
                    name = '', 
                    name_normalized = '', 
                    level = 1.337, 
                    code = '', ),
                administrative_level3 = realzilla.client.models.external_administrative_level_shallow.ExternalAdministrativeLevelShallow(
                    id = '', 
                    name = '', 
                    name_normalized = '', 
                    level = 1.337, 
                    code = '', ),
                administrative_level4 = realzilla.client.models.external_administrative_level_shallow.ExternalAdministrativeLevelShallow(
                    id = '', 
                    name = '', 
                    name_normalized = '', 
                    level = 1.337, 
                    code = '', )
            )
        else:
            return ExternalCity(
                id = '',
                code = '',
                name = '',
                name_normalized = '',
                status = 'ACTIVE',
                population = 1.337,
                surface = 1.337,
                density = 1.337,
        )
        """

    def testExternalCity(self):
        """Test ExternalCity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
