# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.api.admin_web_api import AdminWebApi


class TestAdminWebApi(unittest.TestCase):
    """AdminWebApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminWebApi()

    def tearDown(self) -> None:
        pass

    def test_admin_web_webpages_post(self) -> None:
        """Test case for admin_web_webpages_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
