# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from realzilla.client.models.web_asset_status import WebAssetStatus

class TestWebAssetStatus(unittest.TestCase):
    """WebAssetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebAssetStatus(self):
        """Test WebAssetStatus"""
        # inst = WebAssetStatus()

if __name__ == '__main__':
    unittest.main()
