# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from realzilla.client.models.error_response import ErrorResponse
from realzilla.client.models.simple_response import SimpleResponse
from typing import Optional, Set
from typing_extensions import Self

class DefaultSimpleResponse(BaseModel):
    """
    DefaultSimpleResponse
    """ # noqa: E501
    var_2xx: SimpleResponse = Field(alias="2xx")
    var_4xx: ErrorResponse = Field(alias="4xx")
    var_5xx: ErrorResponse = Field(alias="5xx")
    __properties: ClassVar[List[str]] = ["2xx", "4xx", "5xx"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefaultSimpleResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_2xx
        if self.var_2xx:
            _dict['2xx'] = self.var_2xx.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_4xx
        if self.var_4xx:
            _dict['4xx'] = self.var_4xx.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_5xx
        if self.var_5xx:
            _dict['5xx'] = self.var_5xx.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefaultSimpleResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "2xx": SimpleResponse.from_dict(obj["2xx"]) if obj.get("2xx") is not None else None,
            "4xx": ErrorResponse.from_dict(obj["4xx"]) if obj.get("4xx") is not None else None,
            "5xx": ErrorResponse.from_dict(obj["5xx"]) if obj.get("5xx") is not None else None
        })
        return _obj


