# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from realzilla.client.models.external_agency import ExternalAgency
from realzilla.client.models.external_agent import ExternalAgent
from realzilla.client.models.external_property import ExternalProperty
from realzilla.client.models.heating_type import HeatingType
from realzilla.client.models.listing_status import ListingStatus
from typing import Optional, Set
from typing_extensions import Self

class ExternalListing(BaseModel):
    """
    ExternalListing
    """ # noqa: E501
    id: StrictStr
    status: ListingStatus
    url: StrictStr
    title: StrictStr
    description: StrictStr
    price_listed: StrictStr = Field(alias="priceListed")
    agency_fee: Optional[StrictStr] = Field(alias="agencyFee")
    agency_commission: Optional[StrictStr] = Field(alias="agencyCommission")
    info_year: Optional[Union[StrictFloat, StrictInt]] = Field(alias="infoYear")
    info_pool: Optional[StrictBool] = Field(alias="infoPool")
    info_elevator: Optional[StrictBool] = Field(alias="infoElevator")
    info_floor: Optional[Union[StrictFloat, StrictInt]] = Field(alias="infoFloor")
    info_num_floors: Optional[Union[StrictFloat, StrictInt]] = Field(alias="infoNumFloors")
    info_heating: Optional[HeatingType] = Field(alias="infoHeating")
    info_terrace: Optional[StrictBool] = Field(alias="infoTerrace")
    file_path: StrictStr = Field(alias="filePath")
    var_property: Optional[ExternalProperty] = Field(default=None, alias="property")
    agent1: Optional[ExternalAgent] = None
    agent2: Optional[ExternalAgent] = None
    agency: Optional[ExternalAgency] = None
    agency_parent: Optional[ExternalAgency] = Field(default=None, alias="agencyParent")
    __properties: ClassVar[List[str]] = ["id", "status", "url", "title", "description", "priceListed", "agencyFee", "agencyCommission", "infoYear", "infoPool", "infoElevator", "infoFloor", "infoNumFloors", "infoHeating", "infoTerrace", "filePath", "property", "agent1", "agent2", "agency", "agencyParent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_property
        if self.var_property:
            _dict['property'] = self.var_property.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agent1
        if self.agent1:
            _dict['agent1'] = self.agent1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agent2
        if self.agent2:
            _dict['agent2'] = self.agent2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agency
        if self.agency:
            _dict['agency'] = self.agency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agency_parent
        if self.agency_parent:
            _dict['agencyParent'] = self.agency_parent.to_dict()
        # set to None if agency_fee (nullable) is None
        # and model_fields_set contains the field
        if self.agency_fee is None and "agency_fee" in self.model_fields_set:
            _dict['agencyFee'] = None

        # set to None if agency_commission (nullable) is None
        # and model_fields_set contains the field
        if self.agency_commission is None and "agency_commission" in self.model_fields_set:
            _dict['agencyCommission'] = None

        # set to None if info_year (nullable) is None
        # and model_fields_set contains the field
        if self.info_year is None and "info_year" in self.model_fields_set:
            _dict['infoYear'] = None

        # set to None if info_pool (nullable) is None
        # and model_fields_set contains the field
        if self.info_pool is None and "info_pool" in self.model_fields_set:
            _dict['infoPool'] = None

        # set to None if info_elevator (nullable) is None
        # and model_fields_set contains the field
        if self.info_elevator is None and "info_elevator" in self.model_fields_set:
            _dict['infoElevator'] = None

        # set to None if info_floor (nullable) is None
        # and model_fields_set contains the field
        if self.info_floor is None and "info_floor" in self.model_fields_set:
            _dict['infoFloor'] = None

        # set to None if info_num_floors (nullable) is None
        # and model_fields_set contains the field
        if self.info_num_floors is None and "info_num_floors" in self.model_fields_set:
            _dict['infoNumFloors'] = None

        # set to None if info_heating (nullable) is None
        # and model_fields_set contains the field
        if self.info_heating is None and "info_heating" in self.model_fields_set:
            _dict['infoHeating'] = None

        # set to None if info_terrace (nullable) is None
        # and model_fields_set contains the field
        if self.info_terrace is None and "info_terrace" in self.model_fields_set:
            _dict['infoTerrace'] = None

        # set to None if agent1 (nullable) is None
        # and model_fields_set contains the field
        if self.agent1 is None and "agent1" in self.model_fields_set:
            _dict['agent1'] = None

        # set to None if agent2 (nullable) is None
        # and model_fields_set contains the field
        if self.agent2 is None and "agent2" in self.model_fields_set:
            _dict['agent2'] = None

        # set to None if agency_parent (nullable) is None
        # and model_fields_set contains the field
        if self.agency_parent is None and "agency_parent" in self.model_fields_set:
            _dict['agencyParent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "url": obj.get("url"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "priceListed": obj.get("priceListed"),
            "agencyFee": obj.get("agencyFee"),
            "agencyCommission": obj.get("agencyCommission"),
            "infoYear": obj.get("infoYear"),
            "infoPool": obj.get("infoPool"),
            "infoElevator": obj.get("infoElevator"),
            "infoFloor": obj.get("infoFloor"),
            "infoNumFloors": obj.get("infoNumFloors"),
            "infoHeating": obj.get("infoHeating"),
            "infoTerrace": obj.get("infoTerrace"),
            "filePath": obj.get("filePath"),
            "property": ExternalProperty.from_dict(obj["property"]) if obj.get("property") is not None else None,
            "agent1": ExternalAgent.from_dict(obj["agent1"]) if obj.get("agent1") is not None else None,
            "agent2": ExternalAgent.from_dict(obj["agent2"]) if obj.get("agent2") is not None else None,
            "agency": ExternalAgency.from_dict(obj["agency"]) if obj.get("agency") is not None else None,
            "agencyParent": ExternalAgency.from_dict(obj["agencyParent"]) if obj.get("agencyParent") is not None else None
        })
        return _obj


