# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from realzilla.client.models.external_listing import ExternalListing
from realzilla.client.models.external_property import ExternalProperty
from typing import Optional, Set
from typing_extensions import Self

class ExternalSale(BaseModel):
    """
    ExternalSale
    """ # noqa: E501
    id: StrictStr
    price_listed: Optional[Union[StrictFloat, StrictInt]] = Field(alias="priceListed")
    price_final: Union[StrictFloat, StrictInt] = Field(alias="priceFinal")
    agency_fee: Optional[Union[StrictFloat, StrictInt]] = Field(alias="agencyFee")
    agency_commission: Optional[Union[StrictFloat, StrictInt]] = Field(alias="agencyCommission")
    var_property: Optional[ExternalProperty] = Field(default=None, alias="property")
    listing: Optional[ExternalListing] = None
    __properties: ClassVar[List[str]] = ["id", "priceListed", "priceFinal", "agencyFee", "agencyCommission", "property", "listing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalSale from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_property
        if self.var_property:
            _dict['property'] = self.var_property.to_dict()
        # override the default output from pydantic by calling `to_dict()` of listing
        if self.listing:
            _dict['listing'] = self.listing.to_dict()
        # set to None if price_listed (nullable) is None
        # and model_fields_set contains the field
        if self.price_listed is None and "price_listed" in self.model_fields_set:
            _dict['priceListed'] = None

        # set to None if agency_fee (nullable) is None
        # and model_fields_set contains the field
        if self.agency_fee is None and "agency_fee" in self.model_fields_set:
            _dict['agencyFee'] = None

        # set to None if agency_commission (nullable) is None
        # and model_fields_set contains the field
        if self.agency_commission is None and "agency_commission" in self.model_fields_set:
            _dict['agencyCommission'] = None

        # set to None if listing (nullable) is None
        # and model_fields_set contains the field
        if self.listing is None and "listing" in self.model_fields_set:
            _dict['listing'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalSale from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "priceListed": obj.get("priceListed"),
            "priceFinal": obj.get("priceFinal"),
            "agencyFee": obj.get("agencyFee"),
            "agencyCommission": obj.get("agencyCommission"),
            "property": ExternalProperty.from_dict(obj["property"]) if obj.get("property") is not None else None,
            "listing": ExternalListing.from_dict(obj["listing"]) if obj.get("listing") is not None else None
        })
        return _obj


