# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from realzilla.client.models.city_status import CityStatus
from realzilla.client.models.external_administrative_level_shallow import ExternalAdministrativeLevelShallow
from typing import Optional, Set
from typing_extensions import Self

class ExternalCity(BaseModel):
    """
    ExternalCity
    """ # noqa: E501
    id: StrictStr
    code: StrictStr
    name: StrictStr
    name_normalized: StrictStr = Field(alias="nameNormalized")
    status: CityStatus
    population: Optional[Union[StrictFloat, StrictInt]]
    surface: Optional[Union[StrictFloat, StrictInt]]
    density: Optional[Union[StrictFloat, StrictInt]]
    administrative_level1: Optional[ExternalAdministrativeLevelShallow] = Field(default=None, alias="administrativeLevel1")
    administrative_level2: Optional[ExternalAdministrativeLevelShallow] = Field(default=None, alias="administrativeLevel2")
    administrative_level3: Optional[ExternalAdministrativeLevelShallow] = Field(default=None, alias="administrativeLevel3")
    administrative_level4: Optional[ExternalAdministrativeLevelShallow] = Field(default=None, alias="administrativeLevel4")
    __properties: ClassVar[List[str]] = ["id", "code", "name", "nameNormalized", "status", "population", "surface", "density", "administrativeLevel1", "administrativeLevel2", "administrativeLevel3", "administrativeLevel4"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalCity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of administrative_level1
        if self.administrative_level1:
            _dict['administrativeLevel1'] = self.administrative_level1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of administrative_level2
        if self.administrative_level2:
            _dict['administrativeLevel2'] = self.administrative_level2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of administrative_level3
        if self.administrative_level3:
            _dict['administrativeLevel3'] = self.administrative_level3.to_dict()
        # override the default output from pydantic by calling `to_dict()` of administrative_level4
        if self.administrative_level4:
            _dict['administrativeLevel4'] = self.administrative_level4.to_dict()
        # set to None if population (nullable) is None
        # and model_fields_set contains the field
        if self.population is None and "population" in self.model_fields_set:
            _dict['population'] = None

        # set to None if surface (nullable) is None
        # and model_fields_set contains the field
        if self.surface is None and "surface" in self.model_fields_set:
            _dict['surface'] = None

        # set to None if density (nullable) is None
        # and model_fields_set contains the field
        if self.density is None and "density" in self.model_fields_set:
            _dict['density'] = None

        # set to None if administrative_level1 (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level1 is None and "administrative_level1" in self.model_fields_set:
            _dict['administrativeLevel1'] = None

        # set to None if administrative_level2 (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level2 is None and "administrative_level2" in self.model_fields_set:
            _dict['administrativeLevel2'] = None

        # set to None if administrative_level3 (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level3 is None and "administrative_level3" in self.model_fields_set:
            _dict['administrativeLevel3'] = None

        # set to None if administrative_level4 (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level4 is None and "administrative_level4" in self.model_fields_set:
            _dict['administrativeLevel4'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalCity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "name": obj.get("name"),
            "nameNormalized": obj.get("nameNormalized"),
            "status": obj.get("status"),
            "population": obj.get("population"),
            "surface": obj.get("surface"),
            "density": obj.get("density"),
            "administrativeLevel1": ExternalAdministrativeLevelShallow.from_dict(obj["administrativeLevel1"]) if obj.get("administrativeLevel1") is not None else None,
            "administrativeLevel2": ExternalAdministrativeLevelShallow.from_dict(obj["administrativeLevel2"]) if obj.get("administrativeLevel2") is not None else None,
            "administrativeLevel3": ExternalAdministrativeLevelShallow.from_dict(obj["administrativeLevel3"]) if obj.get("administrativeLevel3") is not None else None,
            "administrativeLevel4": ExternalAdministrativeLevelShallow.from_dict(obj["administrativeLevel4"]) if obj.get("administrativeLevel4") is not None else None
        })
        return _obj


