# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from realzilla.client.models.administrative_level_type import AdministrativeLevelType
from realzilla.client.models.country_code import CountryCode
from typing import Optional, Set
from typing_extensions import Self

class ExternalCountry(BaseModel):
    """
    ExternalCountry
    """ # noqa: E501
    id: StrictStr
    code: CountryCode
    name: StrictStr
    name_normalized: StrictStr = Field(alias="nameNormalized")
    population: Optional[Union[StrictFloat, StrictInt]]
    surface: Optional[Union[StrictFloat, StrictInt]]
    administrative_level1_type: Optional[AdministrativeLevelType] = Field(alias="administrativeLevel1Type")
    administrative_level1_name: Optional[StrictStr] = Field(alias="administrativeLevel1Name")
    administrative_level2_type: Optional[AdministrativeLevelType] = Field(alias="administrativeLevel2Type")
    administrative_level2_name: Optional[StrictStr] = Field(alias="administrativeLevel2Name")
    administrative_level3_type: Optional[AdministrativeLevelType] = Field(alias="administrativeLevel3Type")
    administrative_level3_name: Optional[StrictStr] = Field(alias="administrativeLevel3Name")
    administrative_level4_type: Optional[AdministrativeLevelType] = Field(alias="administrativeLevel4Type")
    administrative_level4_name: Optional[StrictStr] = Field(alias="administrativeLevel4Name")
    __properties: ClassVar[List[str]] = ["id", "code", "name", "nameNormalized", "population", "surface", "administrativeLevel1Type", "administrativeLevel1Name", "administrativeLevel2Type", "administrativeLevel2Name", "administrativeLevel3Type", "administrativeLevel3Name", "administrativeLevel4Type", "administrativeLevel4Name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalCountry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if population (nullable) is None
        # and model_fields_set contains the field
        if self.population is None and "population" in self.model_fields_set:
            _dict['population'] = None

        # set to None if surface (nullable) is None
        # and model_fields_set contains the field
        if self.surface is None and "surface" in self.model_fields_set:
            _dict['surface'] = None

        # set to None if administrative_level1_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level1_type is None and "administrative_level1_type" in self.model_fields_set:
            _dict['administrativeLevel1Type'] = None

        # set to None if administrative_level1_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level1_name is None and "administrative_level1_name" in self.model_fields_set:
            _dict['administrativeLevel1Name'] = None

        # set to None if administrative_level2_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level2_type is None and "administrative_level2_type" in self.model_fields_set:
            _dict['administrativeLevel2Type'] = None

        # set to None if administrative_level2_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level2_name is None and "administrative_level2_name" in self.model_fields_set:
            _dict['administrativeLevel2Name'] = None

        # set to None if administrative_level3_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level3_type is None and "administrative_level3_type" in self.model_fields_set:
            _dict['administrativeLevel3Type'] = None

        # set to None if administrative_level3_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level3_name is None and "administrative_level3_name" in self.model_fields_set:
            _dict['administrativeLevel3Name'] = None

        # set to None if administrative_level4_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level4_type is None and "administrative_level4_type" in self.model_fields_set:
            _dict['administrativeLevel4Type'] = None

        # set to None if administrative_level4_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level4_name is None and "administrative_level4_name" in self.model_fields_set:
            _dict['administrativeLevel4Name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalCountry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "name": obj.get("name"),
            "nameNormalized": obj.get("nameNormalized"),
            "population": obj.get("population"),
            "surface": obj.get("surface"),
            "administrativeLevel1Type": obj.get("administrativeLevel1Type"),
            "administrativeLevel1Name": obj.get("administrativeLevel1Name"),
            "administrativeLevel2Type": obj.get("administrativeLevel2Type"),
            "administrativeLevel2Name": obj.get("administrativeLevel2Name"),
            "administrativeLevel3Type": obj.get("administrativeLevel3Type"),
            "administrativeLevel3Name": obj.get("administrativeLevel3Name"),
            "administrativeLevel4Type": obj.get("administrativeLevel4Type"),
            "administrativeLevel4Name": obj.get("administrativeLevel4Name")
        })
        return _obj


