# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from realzilla.client.models.external_city import ExternalCity
from realzilla.client.models.external_country import ExternalCountry
from realzilla.client.models.external_search_entry import ExternalSearchEntry
from realzilla.client.models.search_query_status import SearchQueryStatus
from typing import Optional, Set
from typing_extensions import Self

class ExternalSearchQuery(BaseModel):
    """
    ExternalSearchQuery
    """ # noqa: E501
    id: StrictStr
    text: StrictStr
    status: SearchQueryStatus
    population: Optional[Union[StrictFloat, StrictInt]]
    search_entry: Optional[ExternalSearchEntry] = Field(default=None, alias="searchEntry")
    city: Optional[ExternalCity] = None
    country: Optional[ExternalCountry] = None
    __properties: ClassVar[List[str]] = ["id", "text", "status", "population", "searchEntry", "city", "country"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalSearchQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of search_entry
        if self.search_entry:
            _dict['searchEntry'] = self.search_entry.to_dict()
        # override the default output from pydantic by calling `to_dict()` of city
        if self.city:
            _dict['city'] = self.city.to_dict()
        # override the default output from pydantic by calling `to_dict()` of country
        if self.country:
            _dict['country'] = self.country.to_dict()
        # set to None if population (nullable) is None
        # and model_fields_set contains the field
        if self.population is None and "population" in self.model_fields_set:
            _dict['population'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalSearchQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "text": obj.get("text"),
            "status": obj.get("status"),
            "population": obj.get("population"),
            "searchEntry": ExternalSearchEntry.from_dict(obj["searchEntry"]) if obj.get("searchEntry") is not None else None,
            "city": ExternalCity.from_dict(obj["city"]) if obj.get("city") is not None else None,
            "country": ExternalCountry.from_dict(obj["country"]) if obj.get("country") is not None else None
        })
        return _obj


