# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FetchComplexity(str, Enum):
    """
    FetchComplexity
    """

    """
    allowed enum values
    """
    REQUEST = 'REQUEST'
    PROXIED_REQUEST = 'PROXIED_REQUEST'
    BROWSER_HEADLESS_NO_IMG = 'BROWSER_HEADLESS_NO_IMG'
    BROWSER_HEADLESS = 'BROWSER_HEADLESS'
    BROWSER_NO_IMG = 'BROWSER_NO_IMG'
    BROWSER = 'BROWSER'
    ESCALATE1 = 'ESCALATE1'
    ESCALATE2 = 'ESCALATE2'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FetchComplexity from a JSON string"""
        return cls(json.loads(json_str))


