# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GeoCountriesCountryCodeGet200ResponseDataCountry(BaseModel):
    """
    GeoCountriesCountryCodeGet200ResponseDataCountry
    """ # noqa: E501
    id: StrictStr
    code: StrictStr = Field(description="249 officially assigned country codes, 13 exceptional reservations, and 7 transitional reservations")
    name: StrictStr
    name_normalized: StrictStr = Field(alias="nameNormalized")
    population: Optional[Union[StrictFloat, StrictInt]]
    surface: Optional[Union[StrictFloat, StrictInt]]
    administrative_level1_type: Optional[StrictStr] = Field(alias="administrativeLevel1Type")
    administrative_level1_name: Optional[StrictStr] = Field(alias="administrativeLevel1Name")
    administrative_level2_type: Optional[StrictStr] = Field(alias="administrativeLevel2Type")
    administrative_level2_name: Optional[StrictStr] = Field(alias="administrativeLevel2Name")
    administrative_level3_type: Optional[StrictStr] = Field(alias="administrativeLevel3Type")
    administrative_level3_name: Optional[StrictStr] = Field(alias="administrativeLevel3Name")
    administrative_level4_type: Optional[StrictStr] = Field(alias="administrativeLevel4Type")
    administrative_level4_name: Optional[StrictStr] = Field(alias="administrativeLevel4Name")
    __properties: ClassVar[List[str]] = ["id", "code", "name", "nameNormalized", "population", "surface", "administrativeLevel1Type", "administrativeLevel1Name", "administrativeLevel2Type", "administrativeLevel2Name", "administrativeLevel3Type", "administrativeLevel3Name", "administrativeLevel4Type", "administrativeLevel4Name"]

    @field_validator('code')
    def code_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW', 'AC', 'CP', 'CQ', 'DG', 'EA', 'EU', 'EZ', 'FX', 'IC', 'SU', 'TA', 'UK', 'UN', 'AN', 'BU', 'CS', 'NT', 'TP', 'YU', 'ZR']):
            raise ValueError("must be one of enum values ('AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW', 'AC', 'CP', 'CQ', 'DG', 'EA', 'EU', 'EZ', 'FX', 'IC', 'SU', 'TA', 'UK', 'UN', 'AN', 'BU', 'CS', 'NT', 'TP', 'YU', 'ZR')")
        return value

    @field_validator('administrative_level1_type')
    def administrative_level1_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER']):
            raise ValueError("must be one of enum values ('STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER')")
        return value

    @field_validator('administrative_level2_type')
    def administrative_level2_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER']):
            raise ValueError("must be one of enum values ('STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER')")
        return value

    @field_validator('administrative_level3_type')
    def administrative_level3_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER']):
            raise ValueError("must be one of enum values ('STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER')")
        return value

    @field_validator('administrative_level4_type')
    def administrative_level4_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER']):
            raise ValueError("must be one of enum values ('STATE', 'REGION', 'PROVINCE', 'DEPARTMENT', 'DISTRICT', 'COUNTY', 'OTHER')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeoCountriesCountryCodeGet200ResponseDataCountry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if population (nullable) is None
        # and model_fields_set contains the field
        if self.population is None and "population" in self.model_fields_set:
            _dict['population'] = None

        # set to None if surface (nullable) is None
        # and model_fields_set contains the field
        if self.surface is None and "surface" in self.model_fields_set:
            _dict['surface'] = None

        # set to None if administrative_level1_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level1_type is None and "administrative_level1_type" in self.model_fields_set:
            _dict['administrativeLevel1Type'] = None

        # set to None if administrative_level1_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level1_name is None and "administrative_level1_name" in self.model_fields_set:
            _dict['administrativeLevel1Name'] = None

        # set to None if administrative_level2_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level2_type is None and "administrative_level2_type" in self.model_fields_set:
            _dict['administrativeLevel2Type'] = None

        # set to None if administrative_level2_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level2_name is None and "administrative_level2_name" in self.model_fields_set:
            _dict['administrativeLevel2Name'] = None

        # set to None if administrative_level3_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level3_type is None and "administrative_level3_type" in self.model_fields_set:
            _dict['administrativeLevel3Type'] = None

        # set to None if administrative_level3_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level3_name is None and "administrative_level3_name" in self.model_fields_set:
            _dict['administrativeLevel3Name'] = None

        # set to None if administrative_level4_type (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level4_type is None and "administrative_level4_type" in self.model_fields_set:
            _dict['administrativeLevel4Type'] = None

        # set to None if administrative_level4_name (nullable) is None
        # and model_fields_set contains the field
        if self.administrative_level4_name is None and "administrative_level4_name" in self.model_fields_set:
            _dict['administrativeLevel4Name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeoCountriesCountryCodeGet200ResponseDataCountry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "name": obj.get("name"),
            "nameNormalized": obj.get("nameNormalized"),
            "population": obj.get("population"),
            "surface": obj.get("surface"),
            "administrativeLevel1Type": obj.get("administrativeLevel1Type"),
            "administrativeLevel1Name": obj.get("administrativeLevel1Name"),
            "administrativeLevel2Type": obj.get("administrativeLevel2Type"),
            "administrativeLevel2Name": obj.get("administrativeLevel2Name"),
            "administrativeLevel3Type": obj.get("administrativeLevel3Type"),
            "administrativeLevel3Name": obj.get("administrativeLevel3Name"),
            "administrativeLevel4Type": obj.get("administrativeLevel4Type"),
            "administrativeLevel4Name": obj.get("administrativeLevel4Name")
        })
        return _obj


