# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GeoLevel(str, Enum):
    """
    GeoLevel
    """

    """
    allowed enum values
    """
    COUNTRY = 'COUNTRY'
    ADMINISTRATIVE_LEVEL = 'ADMINISTRATIVE_LEVEL'
    CITY = 'CITY'
    SUBDIVISION = 'SUBDIVISION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeoLevel from a JSON string"""
        return cls(json.loads(json_str))


