# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PropertyType(str, Enum):
    """
    PropertyType
    """

    """
    allowed enum values
    """
    RESIDENTIAL = 'RESIDENTIAL'
    COMMERCIAL = 'COMMERCIAL'
    LAND = 'LAND'
    INDUSTRIAL = 'INDUSTRIAL'
    AGRICULTURAL = 'AGRICULTURAL'
    OTHER = 'OTHER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PropertyType from a JSON string"""
        return cls(json.loads(json_str))


