# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ResponseDetail(int, Enum):
    """
    ResponseDetail
    """

    """
    allowed enum values
    """
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_4 = 4
    NUMBER_5 = 5
    NUMBER_6 = 6
    NUMBER_10 = 10
    NUMBER_20 = 20
    NUMBER_30 = 30
    NUMBER_40 = 40

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ResponseDetail from a JSON string"""
        return cls(json.loads(json_str))


