# coding: utf-8

"""
    Realzilla API

    Realzilla backend API documentation

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SearchQueryStatus(str, Enum):
    """
    SearchQueryStatus
    """

    """
    allowed enum values
    """
    NEW = 'NEW'
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SearchQueryStatus from a JSON string"""
        return cls(json.loads(json_str))


